name: Publish To Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application
        uses: actions/checkout@v3
      - name: "Build and deploy application"
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GATSBY_PUBLISH_ACCESS_TOKEN }}
          deploy-branch: gh-pages
